name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use Node.js 16 or another compatible version

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc  # Compile TypeScript code to JavaScript

      - name: Build verification
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed: dist folder not found"
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs only if build is successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure same version as build job

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # This will run the test script from package.json
